// ══════════════════════════════════════════════════════════
//  TOPIC_META: 7장 반복문 (while / do-while / for / break / continue / goto)
// ══════════════════════════════════════════════════════════
window.TOPIC_META = [
  { group: 'while 문', key: 'whilebasic', label: '03whilebasic', sub: 'while 기본 구조', icon: '🌀', isSub: false },
  { group: 'do-while 문', key: 'dowhile', label: '05dowhile', sub: '커피 주문 메뉴 (센티널)', icon: '↩', isSub: false },
  { group: 'for 문', key: 'forbasic', label: '06forbasic', sub: 'for 기본 구조', icon: '🔁', isSub: false },
  { group: 'for 문', key: 'triangle', label: '16triangle', sub: '중첩 for 삼각형', tag: 'NEST', tagStyle: 'purple', isSub: true },
  { group: '분기문', key: 'breakstmt', label: '11break', sub: 'break로 0 입력 시 종료', icon: '⛔', isSub: false },
  { group: '분기문', key: 'continuestmt', label: '12continue', sub: '3의 배수 건너뛰기', icon: '⏭', isSub: false },
  { group: '분기문', key: 'gotostmt', label: '13goto', sub: 'goto 레이블 점프 ⚠', icon: '🏹', isSub: false },
  { group: '실습', key: 'lab1max', label: 'lab1max', sub: 'while 키 130cm 이하 정원', icon: '📏', isSub: false },
  { group: '실습', key: 'lab2digit', label: 'lab2digit', sub: 'do-while 자릿수 분리', icon: '🔢', isSub: false },
  { group: '실습', key: 'lab3prime', label: 'lab3primebreak', sub: 'for+break 소수 판별', icon: '🔺', isSub: false },
  { group: '실습', key: 'lab4mtable', label: 'lab4mtable', sub: '중첩 for 구구단', icon: '✖', isSub: false },
];

// ══════════════════════════════════════════════════════════
//  DATA: 각 토픽 정의
// ══════════════════════════════════════════════════════════

window.TOPICS = {

  // ── 03whilebasic: while 기본 ───────────────────────────
  whilebasic: {
    name: '03whilebasic.c',
    title: 'while 문 기본 구조',
    varTypes: { count: 'int' },
    concept: `<b>while (조건식)</b> — 조건을 <b>먼저 검사</b>하고 참이면 반복 몸체 실행.<br>
제어 변수 <code>count</code>를 반복마다 변경하여 조건이 거짓이 되면 루프 탈출.<br>
💡 반복이 끝난 후 count는 조건을 벗어나는 값(4)이 됩니다.`,
    vars: { count: null },
    baseAddr: { count: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">count</span> = <span class="nm">1</span>;` },
      { text: ``, blank: true },
      { id: 'wc', text: `    <span class="kw">while</span> (<span class="vr">count</span> <= <span class="nm">3</span>) {` },
      { id: 'pr', text: `        <span class="fn-c">printf</span>(<span class="st">"반복, 재미있네요!\\n"</span>);`, indent: 1 },
      { id: 'inc', text: `        <span class="vr">count</span>++;`, indent: 1 },
      { text: `    };`, blank: true },
      { id: 'pr2', text: `    <span class="fn-c">printf</span>(<span class="st">"\\n제어 변수 count => %d\\n"</span>, <span class="vr">count</span>);` },
      { text: ``, blank: true },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { count: 1 }, explain: `<b>int count = 1;</b> — 제어 변수 초기화.`, output: null },
      { line: 'wc', type: 'exec', cond: true, vars: { count: 1 }, explain: `<b>조건:</b> count(1) <= 3? → <span class="e-exec">참</span>. 루프 진입.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복, 재미있네요!\\n").`, output: '반복, 재미있네요!' },
      { line: 'inc', type: 'exec', vars: { count: 2 }, explain: `count++ → count = <b>2</b>.`, output: null },
      { line: 'wc', type: 'exec', cond: true, vars: { count: 2 }, explain: `<b>조건:</b> count(2) <= 3? → <span class="e-exec">참</span>.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복, 재미있네요!\\n").`, output: '반복, 재미있네요!' },
      { line: 'inc', type: 'exec', vars: { count: 3 }, explain: `count++ → count = <b>3</b>.`, output: null },
      { line: 'wc', type: 'exec', cond: true, vars: { count: 3 }, explain: `<b>조건:</b> count(3) <= 3? → <span class="e-exec">참</span>.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복, 재미있네요!\\n").`, output: '반복, 재미있네요!' },
      { line: 'inc', type: 'exec', vars: { count: 4 }, explain: `count++ → count = <b>4</b>.`, output: null },
      { line: 'wc', type: 'exec', cond: false, vars: { count: 4 }, explain: `<b>조건:</b> count(4) <= 3? → <span class="e-skip">거짓!</span> 루프 탈출.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("제어 변수 count => 4\\n") — 반복 후 count는 조건을 벗어나는 값.`, output: '제어 변수 count => 4' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b> — 종료.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 05dowhile: 커피 주문 ───────────────────────────────
  dowhile: {
    name: '05dowhile.c',
    title: 'do-while (커피 주문 메뉴)',
    varTypes: { input: 'int' },
    concept: `<b>do { … } while(조건);</b> — 블록을 <b>먼저 실행</b>한 뒤 조건 검사.<br>
조건과 무관하게 <b class="g">최소 1회는 반드시 실행</b>됩니다.<br>
메뉴 선택, 입력 후 검사하는 구조에 적합합니다. <code>while(input)</code>으로도 쓸 수 있음.`,
    vars: { input: null },
    baseAddr: { input: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#define</span> _CRT_SECURE_NO_WARNINGS`, blank: true },
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">input</span>;` },
      { id: 'dob', text: `    <span class="kw">do</span> {` },
      { id: 'pr1', text: `        <span class="fn-c">printf</span>(<span class="st">"[0]종료 [1]아메리카노 [2]카페라떼 [3]카푸치노 \\n"</span>);`, indent: 1 },
      { id: 'pr2', text: `        <span class="fn-c">printf</span>(<span class="st">"주문할 커피 또는 종료(0)를 입력 >> "</span>);`, indent: 1 },
      { id: 'scan', text: `        <span class="fn-c">scanf</span>(<span class="st">"%d"</span>, &<span class="vr">input</span>);`, indent: 1 },
      { id: 'wc', text: `    } <span class="kw">while</span> (<span class="vr">input</span> != <span class="nm">0</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { input: '???' }, explain: `<b>int input;</b> — 아직 초기화 안 됨.`, output: null },
      { line: 'dob', type: 'exec', explain: `<b>do 블록</b> — 조건과 무관하게 먼저 실행.`, output: null },
      { line: 'pr1', type: 'exec', explain: `메뉴 출력.`, output: '[0]종료 [1]아메리카노 [2]카페라떼 [3]카푸치노' },
      { line: 'pr2', type: 'exec', explain: `입력 프롬프트.`, output: '주문할 커피 또는 종료(0)를 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { input: 1 }, explain: `scanf — 사용자가 <b>1</b> 입력 (시뮬레이션).`, output: '→ 입력: 1' },
      { line: 'wc', type: 'exec', cond: true, vars: { input: 1 }, explain: `<b>조건:</b> input(1) != 0? → <span class="e-exec">참</span>. 다시 반복.`, output: null },
      { line: 'pr1', type: 'exec', explain: `메뉴 다시 출력.`, output: '[0]종료 [1]아메리카노 [2]카페라떼 [3]카푸치노' },
      { line: 'pr2', type: 'exec', explain: `입력 프롬프트.`, output: '주문할 커피 또는 종료(0)를 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { input: 0 }, explain: `scanf — 사용자가 <b>0</b> 입력 (종료).`, output: '→ 입력: 0' },
      { line: 'wc', type: 'exec', cond: false, vars: { input: 0 }, explain: `<b>조건:</b> input(0) != 0? → <span class="e-skip">거짓</span>. 루프 탈출!`, output: null },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b> — 종료.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 06forbasic: for 기본 ───────────────────────────────
  forbasic: {
    name: '06forbasic.c',
    title: 'for 문 기본 구조',
    varTypes: { i: 'int' },
    concept: `<b>for (초기식; 조건식; 증감식)</b> — init/cond/inc가 한 줄에 명시.<br>
순서: <b>초기식 → 조건 검사 → 본문 → 증감식 → 조건 검사 …</b><br>
💡 for 종료 후 제어 변수 i는 조건을 벗어나는 값(6)이 됩니다.`,
    vars: { i: null },
    baseAddr: { i: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: `<span class="pp">#define</span> MAX <span class="nm">5</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'finit', text: `    <span class="kw">for</span> (<span class="vr">i</span> = <span class="nm">1</span>; <span class="vr">i</span> <= MAX; <span class="vr">i</span>++) {` },
      { id: 'pr', text: `        <span class="fn-c">printf</span>(<span class="st">"반복 %d\\n"</span>, <span class="vr">i</span>);`, indent: 1 },
      { text: `    }`, blank: true },
      { id: 'pr2', text: `    <span class="fn-c">printf</span>(<span class="st">"\\nfor 종료 이후 i => %d\\n"</span>, <span class="vr">i</span>);` },
      { text: ``, blank: true },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'finit', type: 'exec', vars: { i: 1 }, explain: `<b>① 초기식:</b> i=1. 조건 i(1)<=5 → <span class="e-exec">참</span>. 루프 진입.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복 1\\n").`, output: '반복 1' },
      { line: 'finit', type: 'exec', vars: { i: 2 }, explain: `<b>④ i++ → i=2.</b> 조건 i(2)<=5 → 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복 2\\n").`, output: '반복 2' },
      { line: 'finit', type: 'exec', vars: { i: 3 }, explain: `i++ → i=3. 조건 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복 3\\n").`, output: '반복 3' },
      { line: 'finit', type: 'exec', vars: { i: 4 }, explain: `i++ → i=4. 조건 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복 4\\n").`, output: '반복 4' },
      { line: 'finit', type: 'exec', vars: { i: 5 }, explain: `i++ → i=5. 조건 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("반복 5\\n").`, output: '반복 5' },
      { line: 'finit', type: 'exec', vars: { i: 6 }, explain: `i++ → i=6. 조건 i(6)<=5 → <span class="e-skip">거짓!</span> 루프 탈출.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("for 종료 이후 i => 6\\n") — 제어 변수는 조건을 벗어나는 값.`, output: 'for 종료 이후 i => 6' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b> — 종료.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 16triangle: 중첩 for 삼각형 ────────────────────────
  triangle: {
    name: '16triangle.c',
    title: '중첩 for (삼각형 출력)',
    varTypes: { i: 'int', j: 'int' },
    concept: `for 안에 for가 중첩 — <b>내부 반복이 외부 변수 i에 의존</b>합니다.<br>
외부 i=1일 때 j는 1~1 (별 1개), i=2일 때 j는 1~2 (별 2개) …<br>
결과: *, **, ***, ****, *****`,
    vars: { i: null, j: null },
    baseAddr: { i: '0x7fff5200', j: '0x7fff51fc' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'max', text: `    <span class="kw">const</span> <span class="ty">int</span> MAX = <span class="nm">5</span>;` },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">i</span>, <span class="vr">j</span>;` },
      { text: ``, blank: true },
      { id: 'fo', text: `    <span class="kw">for</span> (<span class="vr">i</span> = <span class="nm">1</span>; <span class="vr">i</span> <= MAX; <span class="vr">i</span>++) {` },
      { id: 'fi', text: `        <span class="kw">for</span> (<span class="vr">j</span> = <span class="nm">1</span>; <span class="vr">j</span> <= <span class="vr">i</span>; <span class="vr">j</span>++) {`, indent: 1 },
      { id: 'pr', text: `            <span class="fn-c">printf</span>(<span class="st">"*"</span>);`, indent: 2 },
      { text: `        }`, blank: true },
      { id: 'nl', text: `        <span class="fn-c">puts</span>(<span class="st">""</span>);`, indent: 1 },
      { text: `    }`, blank: true },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'fo', type: 'exec', vars: { i: 1 }, explain: `외부 i=1. 조건 1<=5 → 참.`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 1, j: 1 }, explain: `내부 j=1. j<=i(1)? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 1, j: 1 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 1, j: 2 }, explain: `j++ → j=2. j<=1? → <span class="e-skip">거짓</span>. 내부 탈출.`, output: null },
      { line: 'nl', type: 'exec', vars: { i: 1, j: 2 }, explain: `puts("") — 1행 완료, 줄바꿈.`, output: '*' },
      { line: 'fo', type: 'exec', vars: { i: 2 }, explain: `i++ → i=2. 조건 참.`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 2, j: 1 }, explain: `내부 j=1. j<=2? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 2, j: 1 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 2, j: 2 }, explain: `j++ → j=2. j<=2? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 2, j: 2 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 2, j: 3 }, explain: `j++ → j=3. 3<=2? → 거짓. 내부 탈출.`, output: null },
      { line: 'nl', type: 'exec', vars: { i: 2, j: 3 }, explain: `puts("") — 2행 완료.`, output: '**' },
      { line: 'fo', type: 'exec', vars: { i: 3 }, explain: `i++ → i=3. 조건 참.`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 3, j: 1 }, explain: `내부 j=1. j<=3? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 3, j: 1 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 3, j: 2 }, explain: `j++ → j=2.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 3, j: 2 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 3, j: 3 }, explain: `j++ → j=3.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 3, j: 3 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 3, j: 4 }, explain: `j++ → j=4. 4<=3? → 거짓. 내부 탈출.`, output: null },
      { line: 'nl', type: 'exec', vars: { i: 3, j: 4 }, explain: `puts("") — 3행 완료.`, output: '***' },
      { line: 'fo', type: 'exec', vars: { i: 4 }, explain: `i++ → i=4.`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 4, j: 1 }, explain: `내부 j=1. j<=4? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 4, j: 1 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 4, j: 2 }, explain: `j++ → j=2.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 4, j: 2 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 4, j: 3 }, explain: `j++ → j=3.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 4, j: 3 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 4, j: 4 }, explain: `j++ → j=4.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 4, j: 4 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 4, j: 5 }, explain: `j++ → j=5. 5<=4? → 거짓. 탈출.`, output: null },
      { line: 'nl', type: 'exec', vars: { i: 4, j: 5 }, explain: `puts("") — 4행 완료.`, output: '****' },
      { line: 'fo', type: 'exec', vars: { i: 5 }, explain: `i++ → i=5.`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 1 }, explain: `내부 j=1. j<=5? → 참.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 5, j: 1 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 2 }, explain: `j++ → j=2.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 5, j: 2 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 3 }, explain: `j++ → j=3.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 5, j: 3 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 4 }, explain: `j++ → j=4.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 5, j: 4 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 5 }, explain: `j++ → j=5.`, output: null },
      { line: 'pr', type: 'exec', vars: { i: 5, j: 5 }, explain: `printf("*").`, output: null },
      { line: 'fi', type: 'exec', vars: { i: 5, j: 6 }, explain: `j++ → j=6. 6<=5? → 거짓. 탈출.`, output: null },
      { line: 'nl', type: 'exec', vars: { i: 5, j: 6 }, explain: `puts("") — 5행 완료.`, output: '*****' },
      { line: 'fo', type: 'exec', vars: { i: 6 }, explain: `i++ → i=6. 6<=5? → <span class="e-skip">거짓</span>. 외부 탈출.`, output: null },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 11break: break ─────────────────────────────────────
  breakstmt: {
    name: '11break.c',
    title: 'break (0 입력 시 반복 종료)',
    varTypes: { input: 'int' },
    concept: `<b>break</b> — 가장 가까운 반복문을 <b>즉시 탈출</b>합니다.<br>
<code>while(1)</code> 무한 루프 + <code>if (input==0) break;</code> 패턴으로<br>
센티널 값(0) 입력 시 깔끔하게 종료합니다.`,
    vars: { input: null },
    baseAddr: { input: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#define</span> _CRT_SECURE_NO_WARNINGS`, blank: true },
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">input</span>;` },
      { id: 'wc', text: `    <span class="kw">while</span> (<span class="nm">1</span>) {` },
      { id: 'pr1', text: `        <span class="fn-c">printf</span>(<span class="st">"양의 정수 또는 0[종료] 입력 후 [Enter] >> "</span>);`, indent: 1 },
      { id: 'scan', text: `        <span class="fn-c">scanf</span>(<span class="st">"%d"</span>, &<span class="vr">input</span>);`, indent: 1 },
      { id: 'ci', text: `        <span class="kw">if</span> (<span class="vr">input</span> == <span class="nm">0</span>)`, indent: 1 },
      { id: 'brk', text: `            <span class="kw">break</span>;`, indent: 2 },
      { id: 'pr2', text: `        <span class="fn-c">printf</span>(<span class="st">"입력한 정수 %d: 16진수 %#x\\n"</span>, <span class="vr">input</span>, <span class="vr">input</span>);`, indent: 1 },
      { text: `    }`, blank: true },
      { id: 'pr3', text: `    <span class="fn-c">puts</span>(<span class="st">"종료"</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { input: '???' }, explain: `<b>int input;</b> 선언.`, output: null },
      { line: 'wc', type: 'exec', explain: `while(1) — 무한 루프 진입.`, output: null },
      { line: 'pr1', type: 'exec', explain: `프롬프트 출력.`, output: '양의 정수 또는 0[종료] 입력 후 [Enter] >> ' },
      { line: 'scan', type: 'exec', vars: { input: 255 }, explain: `scanf — 사용자가 <b>255</b> 입력.`, output: '→ 입력: 255' },
      { line: 'ci', type: 'exec', cond: false, explain: `input(255) == 0? → <span class="e-skip">거짓</span>. break 건너뜀.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("입력한 정수 255: 16진수 0xff\\n").`, output: '입력한 정수 255: 16진수 0xff' },
      { line: 'wc', type: 'exec', explain: `다시 while(1) — 2회차.`, output: null },
      { line: 'pr1', type: 'exec', explain: `프롬프트.`, output: '양의 정수 또는 0[종료] 입력 후 [Enter] >> ' },
      { line: 'scan', type: 'exec', vars: { input: 16 }, explain: `scanf — <b>16</b> 입력.`, output: '→ 입력: 16' },
      { line: 'ci', type: 'exec', cond: false, explain: `input(16) == 0? → 거짓.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("입력한 정수 16: 16진수 0x10\\n").`, output: '입력한 정수 16: 16진수 0x10' },
      { line: 'wc', type: 'exec', explain: `3회차.`, output: null },
      { line: 'pr1', type: 'exec', explain: `프롬프트.`, output: '양의 정수 또는 0[종료] 입력 후 [Enter] >> ' },
      { line: 'scan', type: 'exec', vars: { input: 0 }, explain: `scanf — <b>0</b> 입력 (종료).`, output: '→ 입력: 0' },
      { line: 'ci', type: 'exec', cond: true, explain: `input(0) == 0? → <span class="e-exec">참!</span>`, output: null },
      { line: 'brk', type: 'exec', explain: `<b class="e-exec">break!</b> 루프 즉시 탈출.`, output: '⛔ break — 루프 탈출' },
      { line: 'pr3', type: 'exec', explain: `puts("종료").`, output: '종료' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 12continue: continue ────────────────────────────────
  continuestmt: {
    name: '12continue.c',
    title: 'continue (3의 배수 건너뛰기)',
    varTypes: { i: 'int' },
    concept: `<b>continue</b> — 현재 반복의 나머지를 건너뛰고 <b>다음 반복</b>으로 이동.<br>
for에서는 증감식(i++)으로, while에서는 조건 검사로 점프.<br>
3의 배수(i%3==0)일 때 printf를 건너뜁니다.`,
    vars: { i: null },
    baseAddr: { i: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'max', text: `    <span class="kw">const</span> <span class="ty">int</span> MAX = <span class="nm">15</span>;` },
      { id: 'pr0', text: `    <span class="fn-c">printf</span>(<span class="st">"1에서 %d까지 정수 중에서 3으로 나누어 떨어지지 않는 수\\n"</span>, MAX);` },
      { id: 'fl', text: `    <span class="kw">for</span> (<span class="ty">int</span> <span class="vr">i</span>=<span class="nm">1</span>; <span class="vr">i</span><=MAX; <span class="vr">i</span>++) {` },
      { id: 'ci', text: `        <span class="kw">if</span> (<span class="vr">i</span> % <span class="nm">3</span> == <span class="nm">0</span>)`, indent: 1 },
      { id: 'cnt', text: `            <span class="kw">continue</span>;`, indent: 2 },
      { id: 'pr', text: `        <span class="fn-c">printf</span>(<span class="st">"%3d"</span>, <span class="vr">i</span>);`, indent: 1 },
      { text: `    }`, blank: true },
      { id: 'nl', text: `    <span class="fn-c">puts</span>(<span class="st">""</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'max', type: 'exec', explain: `const int MAX = 15;`, output: null },
      { line: 'pr0', type: 'exec', explain: `printf("1에서 15까지 정수 중에서 3으로 나누어 떨어지지 않는 수\\n").`, output: '1에서 15까지 정수 중에서 3으로 나누어 떨어지지 않는 수' },
      { line: 'fl', type: 'exec', vars: { i: 1 }, explain: `i=1. 조건 1<=15 → 참.`, output: null },
      { line: 'ci', type: 'exec', cond: false, explain: `1%3==0? → <span class="e-skip">거짓</span>. continue 안 함.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 1).`, output: '  1' },
      { line: 'fl', type: 'exec', vars: { i: 2 }, explain: `i++ → i=2.`, output: null },
      { line: 'ci', type: 'exec', cond: false, explain: `2%3==0? → 거짓.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 2).`, output: '  2' },
      { line: 'fl', type: 'exec', vars: { i: 3 }, explain: `i=3.`, output: null },
      { line: 'ci', type: 'exec', cond: true, explain: `3%3==0? → <span class="e-exec">참!</span> continue 실행.`, output: null },
      { line: 'cnt', type: 'exec', explain: `<b class="e-exec">continue!</b> printf 건너뛰고 i++ → 다음 반복.`, output: '⏭ i=3 건너뜀' },
      { line: 'fl', type: 'exec', vars: { i: 4 }, explain: `i=4.`, output: null },
      { line: 'ci', type: 'exec', cond: false, explain: `4%3==0? → 거짓.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 4).`, output: '  4' },
      { line: 'fl', type: 'exec', vars: { i: 5 }, explain: `i++ → i=5.`, output: null },
      { line: 'ci', type: 'exec', cond: false, explain: `5%3==0? → 거짓.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 5).`, output: '  5' },
      { line: 'fl', type: 'exec', vars: { i: 6 }, explain: `i++ → i=6.`, output: null },
      { line: 'ci', type: 'exec', cond: true, explain: `6%3==0? → <span class="e-exec">참!</span> continue.`, output: null },
      { line: 'cnt', type: 'exec', explain: `i=6 건너뜀.`, output: '⏭ i=6 건너뜀' },
      { line: 'fl', type: 'exec', vars: { i: 15 }, explain: `… i=7~14 중 9,12 건너뜀. i=15까지.`, output: null },
      { line: 'nl', type: 'exec', explain: `puts("") — 줄바꿈.`, output: '  7  8  10  11  13  14' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── 13goto: goto ───────────────────────────────────────
  gotostmt: {
    name: '13goto.c',
    title: 'goto 문 ⚠',
    varTypes: { count: 'int' },
    concept: `<b>goto 레이블;</b> — 지정 위치로 <b>무조건 점프</b>합니다.<br>
<b class="r">실무에서는 사용을 지양합니다.</b> (스파게티 코드, 가독성 저하)<br>
예외: 다중 중첩 루프 탈출, 오류 처리 등 제한적 사용.`,
    vars: { count: null },
    baseAddr: { count: '0x7fff5200' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">count</span> = <span class="nm">1</span>;` },
      { id: 'lbl', text: `<span class="lbl">loop:</span>` },
      { id: 'pr', text: `    <span class="fn-c">printf</span>(<span class="st">"%3d"</span>, <span class="vr">count</span>);` },
      { id: 'ci', text: `    <span class="kw">if</span> (++<span class="vr">count</span> <= <span class="nm">10</span>)` },
      { id: 'gt', text: `        <span class="kw">goto</span> <span class="lbl">loop</span>;` },
      { text: ``, blank: true },
      { id: 'pr2', text: `    <span class="fn-c">printf</span>(<span class="st">"\\n종료\\n"</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { count: 1 }, explain: `<b>count=1</b> 선언.`, output: null },
      { line: 'lbl', type: 'exec', explain: `loop: 레이블 도달.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 1).`, output: '  1' },
      { line: 'ci', type: 'exec', cond: true, vars: { count: 2 }, explain: `++count → 2. 2<=10? → <span class="e-exec">참</span>.`, output: null },
      { line: 'gt', type: 'exec', explain: `<b class="e-exec">goto loop!</b> 위로 점프.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("%3d", 2).`, output: '  2' },
      { line: 'ci', type: 'exec', cond: true, vars: { count: 3 }, explain: `++count → 3. 3<=10? → 참.`, output: null },
      { line: 'gt', type: 'exec', explain: `goto loop.`, output: null },
      { line: 'pr', type: 'exec', explain: `… count 4~10까지 출력.`, output: '  3  4  5  6  7  8  9 10' },
      { line: 'ci', type: 'exec', cond: false, vars: { count: 11 }, explain: `++count → 11. 11<=10? → <span class="e-skip">거짓</span>. goto 건너뜀.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("\\n종료\\n").`, output: '종료' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── lab1max: while 키 130cm 이하 ───────────────────────
  lab1max: {
    name: 'lab1max.c',
    title: '실습: while — 키 130cm 이하 정원 4명',
    varTypes: { num: 'int', height: 'double' },
    concept: `while 조건과 입력 필터링으로 <b>원하는 조건의 정원</b>을 채웁니다.<br>
height <= 130일 때만 num++ → 조건 미충족 입력은 카운트 안 됨.<br>
예: 140, 125, 150, 120, 130, 115 입력 시 4명 완료.`,
    vars: { num: null, height: null },
    baseAddr: { num: '0x7fff5200', height: '0x7fff5208' },
    code: [
      { text: `<span class="pp">#define</span> _CRT_SECURE_NO_WARNINGS`, blank: true },
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: `<span class="pp">#define</span> MAX <span class="nm">4</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>() {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">num</span> = <span class="nm">0</span>;` },
      { id: 'decl2', text: `    <span class="ty">double</span> <span class="vr">height</span> = <span class="nm">0</span>;` },
      { id: 'wc', text: `    <span class="kw">while</span> (<span class="vr">num</span> < MAX) {` },
      { id: 'pr', text: `        <span class="fn-c">printf</span>(<span class="st">"키 입력 >> "</span>);`, indent: 1 },
      { id: 'scan', text: `        <span class="fn-c">scanf</span>(<span class="st">"%lf"</span>, &<span class="vr">height</span>);`, indent: 1 },
      { id: 'ci', text: `        <span class="kw">if</span> (<span class="vr">height</span> <= <span class="nm">130</span>)`, indent: 1 },
      { id: 'inc', text: `            <span class="vr">num</span>++;`, indent: 2 },
      { text: `    }`, blank: true },
      { id: 'pr2', text: `    <span class="fn-c">printf</span>(<span class="st">"정원 %d명 완료!\\n"</span>, <span class="vr">num</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { num: 0, height: 0 }, explain: `num=0, height=0 초기화.`, output: null },
      { line: 'wc', type: 'exec', cond: true, explain: `num(0) < 4? → <span class="e-exec">참</span>.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("키 입력 >> ").`, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 140 }, explain: `scanf — <b>140</b> 입력. 140>130 → num 증가 안 함.`, output: '→ 입력: 140' },
      { line: 'wc', type: 'exec', cond: true, vars: { num: 0 }, explain: `num(0) < 4? → 참. 계속.`, output: null },
      { line: 'pr', type: 'exec', explain: `키 입력 >> `, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 125, num: 1 }, explain: `scanf — <b>125</b>. 125<=130 → num++ → num=1.`, output: '→ 입력: 125' },
      { line: 'wc', type: 'exec', cond: true, explain: `num(1) < 4? → 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("키 입력 >> ").`, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 150 }, explain: `scanf — <b>150</b> 입력. 150>130 → num 증가 안 함.`, output: '→ 입력: 150' },
      { line: 'wc', type: 'exec', cond: true, vars: { num: 1 }, explain: `num(1) < 4? → 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("키 입력 >> ").`, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 120, num: 2 }, explain: `scanf — <b>120</b>. 120<=130 → num++ → num=2.`, output: '→ 입력: 120' },
      { line: 'wc', type: 'exec', cond: true, explain: `num(2) < 4? → 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("키 입력 >> ").`, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 130, num: 3 }, explain: `scanf — <b>130</b>. 130<=130 → num++ → num=3.`, output: '→ 입력: 130' },
      { line: 'wc', type: 'exec', cond: true, explain: `num(3) < 4? → 참.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("키 입력 >> ").`, output: '키 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { height: 115, num: 4 }, explain: `scanf — <b>115</b>. 115<=130 → num++ → num=4.`, output: '→ 입력: 115' },
      { line: 'wc', type: 'exec', cond: false, vars: { num: 4 }, explain: `num(4) < 4? → <span class="e-skip">거짓</span>. 루프 탈출.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("정원 4명 완료!\\n").`, output: '정원 4명 완료!' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── lab2digit: do-while 자릿수 ─────────────────────────
  lab2digit: {
    name: 'lab2digit.c',
    title: '실습: do-while — 세 자리 정수 자릿수',
    varTypes: { input: 'int', result: 'int', digit: 'int', devider: 'int' },
    concept: `do-while + 나눗셈/나머지로 <b>자릿수 분리</b>.<br>
devider를 100→10→1로 줄이면서 백/십/일 자리 추출.<br>
💡 do-while이라 조건과 무관하게 1회는 실행됩니다.`,
    vars: { input: null, result: null, digit: null, devider: null },
    baseAddr: { input: '0x7fff5200', result: '0x7fff5204', digit: '0x7fff5208', devider: '0x7fff520c' },
    code: [
      { text: `<span class="pp">#define</span> _CRT_SECURE_NO_WARNINGS`, blank: true },
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">input</span>=<span class="nm">0</span>, <span class="vr">result</span>=<span class="nm">0</span>, <span class="vr">digit</span>=<span class="nm">0</span>;` },
      { id: 'decl2', text: `    <span class="ty">int</span> <span class="vr">devider</span>=<span class="nm">100</span>;` },
      { id: 'pr', text: `    <span class="fn-c">printf</span>(<span class="st">"양의 정수[100~999] 입력 : "</span>);` },
      { id: 'scan', text: `    <span class="fn-c">scanf</span>(<span class="st">"%d"</span>, &<span class="vr">input</span>);` },
      { id: 'asgn', text: `    <span class="vr">result</span> = <span class="vr">input</span>;` },
      { id: 'dob', text: `    <span class="kw">do</span> {` },
      { id: 'd1', text: `        <span class="vr">digit</span> = <span class="vr">result</span> / <span class="vr">devider</span>;`, indent: 1 },
      { id: 'd2', text: `        <span class="vr">result</span> %= <span class="vr">devider</span>;`, indent: 1 },
      { id: 'pr2', text: `        <span class="fn-c">printf</span>(<span class="st">"%3d단위 출력: %d\\n"</span>, <span class="vr">devider</span>, <span class="vr">digit</span>);`, indent: 1 },
      { id: 'd3', text: `        <span class="vr">devider</span> /= <span class="nm">10</span>;`, indent: 1 },
      { id: 'wc', text: `    } <span class="kw">while</span> (<span class="vr">devider</span> >= <span class="nm">1</span>);` },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { input: 0, result: 0, digit: 0 }, explain: `변수 선언.`, output: null },
      { line: 'decl2', type: 'exec', vars: { devider: 100 }, explain: `devider=100.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("양의 정수[100~999] 입력 : ").`, output: '양의 정수[100~999] 입력 : ' },
      { line: 'scan', type: 'exec', vars: { input: 456 }, explain: `scanf — <b>456</b> 입력.`, output: '→ 입력: 456' },
      { line: 'asgn', type: 'exec', vars: { result: 456 }, explain: `result = 456.`, output: null },
      { line: 'dob', type: 'exec', explain: `do 블록 — 1회 실행.`, output: null },
      { line: 'd1', type: 'exec', vars: { digit: 4 }, explain: `digit = 456/100 = <b>4</b>.`, output: null },
      { line: 'd2', type: 'exec', vars: { result: 56 }, explain: `result %= 100 → result = 56.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("100단위 출력: 4\\n").`, output: '100단위 출력: 4' },
      { line: 'd3', type: 'exec', vars: { devider: 10 }, explain: `devider /= 10 → devider=10.`, output: null },
      { line: 'wc', type: 'exec', cond: true, explain: `devider(10) >= 1? → 참. 반복.`, output: null },
      { line: 'd1', type: 'exec', vars: { digit: 5, result: 6 }, explain: `digit=56/10=5, result=6.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf(" 10단위 출력: 5\\n").`, output: ' 10단위 출력: 5' },
      { line: 'd3', type: 'exec', vars: { devider: 1 }, explain: `devider=1.`, output: null },
      { line: 'wc', type: 'exec', cond: true, explain: `devider(1) >= 1? → 참.`, output: null },
      { line: 'd1', type: 'exec', vars: { digit: 6, result: 0 }, explain: `digit=6/1=6, result=0.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("  1단위 출력: 6\\n").`, output: '  1단위 출력: 6' },
      { line: 'd3', type: 'exec', vars: { devider: 0 }, explain: `devider=0.`, output: null },
      { line: 'wc', type: 'exec', cond: false, explain: `devider(0) >= 1? → <span class="e-skip">거짓</span>. 탈출.`, output: null },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── lab3prime: for+break 소수 ──────────────────────────
  lab3prime: {
    name: 'lab3primebreak.c',
    title: '실습: for + break — 소수 판별',
    varTypes: { num: 'int', j: 'int' },
    concept: `소수 판별: 2~(num-1) 중 나누어 떨어지는 수가 있으면 <b>break</b>.<br>
break 후 <code>j == num</code>이면 소수 (나누어 떨어지는 수 없음).<br>
예: 17 → j가 17까지 증가하면 소수.`,
    vars: { num: null, j: null },
    baseAddr: { num: '0x7fff5200', j: '0x7fff51fc' },
    code: [
      { text: `<span class="pp">#define</span> _CRT_SECURE_NO_WARNINGS`, blank: true },
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>() {`, blank: true },
      { id: 'decl', text: `    <span class="ty">int</span> <span class="vr">num</span>, <span class="vr">j</span>;` },
      { id: 'pr', text: `    <span class="fn-c">printf</span>(<span class="st">"2 이상 양의 정수 입력 >> "</span>);` },
      { id: 'scan', text: `    <span class="fn-c">scanf</span>(<span class="st">"%d"</span>, &<span class="vr">num</span>);` },
      { text: ``, blank: true },
      { id: 'fl', text: `    <span class="kw">for</span> (<span class="vr">j</span>=<span class="nm">2</span>; <span class="vr">j</span><<span class="vr">num</span>; <span class="vr">j</span>++)` },
      { id: 'ci', text: `        <span class="kw">if</span> (<span class="vr">num</span> % <span class="vr">j</span> == <span class="nm">0</span>)` },
      { id: 'brk', text: `            <span class="kw">break</span>;`, indent: 1 },
      { text: ``, blank: true },
      { id: 'c2', text: `    <span class="kw">if</span> (<span class="vr">j</span> == <span class="vr">num</span>)` },
      { id: 'p1', text: `        <span class="fn-c">printf</span>(<span class="st">"%d 소수이다.\\n"</span>, <span class="vr">num</span>);`, indent: 1 },
      { id: 'e1', text: `    <span class="kw">else</span>` },
      { id: 'p2', text: `        <span class="fn-c">printf</span>(<span class="st">"%d 소수가 아니다.\\n"</span>, <span class="vr">num</span>);`, indent: 1 },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'decl', type: 'exec', vars: { num: '???', j: '???' }, explain: `<b>int num, j;</b> 선언.`, output: null },
      { line: 'pr', type: 'exec', explain: `printf("2 이상 양의 정수 입력 >> ").`, output: '2 이상 양의 정수 입력 >> ' },
      { line: 'scan', type: 'exec', vars: { num: 17 }, explain: `scanf — <b>17</b> 입력.`, output: '→ 입력: 17' },
      { line: 'fl', type: 'exec', vars: { j: 2 }, explain: `j=2. j(2) < 17? → 참.`, output: null },
      { line: 'ci', type: 'exec', cond: false, explain: `17%2==0? → 거짓. break 안 함.`, output: null },
      { line: 'fl', type: 'exec', vars: { j: 3 }, explain: `j++ → j=3. 17%3? → 거짓.`, output: null },
      { line: 'fl', type: 'exec', vars: { j: 4 }, explain: `j=4. 17%4? → 거짓.`, output: null },
      { line: 'fl', type: 'exec', vars: { j: 16 }, explain: `… j=5~16 모두 17로 나누어떨어지지 않음.`, output: null },
      { line: 'fl', type: 'exec', vars: { j: 17 }, explain: `j++ → j=17. j(17) < 17? → <span class="e-skip">거짓</span>. 루프 종료.`, output: null },
      { line: 'c2', type: 'exec', cond: true, explain: `j(17) == num(17)? → <span class="e-exec">참!</span> 소수.`, output: null },
      { line: 'p1', type: 'exec', explain: `printf("17 소수이다.\\n").`, output: '17 소수이다.' },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

  // ── lab4mtable: 구구단 ──────────────────────────────────
  lab4mtable: {
    name: 'lab4mtable.c',
    title: '실습: 중첩 for — 구구단',
    varTypes: { i: 'int', j: 'int' },
    concept: `외부 for: 단(i) 2~9. 내부 for: 곱(j) 2~9.<br>
외부 1회 순환 시 내부 8회 실행 → 총 64회 반복.<br>
2*2=4, 2*3=6, … 9*9=81`,
    vars: { i: null, j: null },
    baseAddr: { i: '0x7fff5200', j: '0x7fff51fc' },
    code: [
      { text: `<span class="pp">#include</span> <span class="st">&lt;stdio.h&gt;</span>`, blank: true },
      { text: `<span class="pp">#define</span> MAX <span class="nm">9</span>`, blank: true },
      { text: ``, blank: true },
      { text: `<span class="ty">int</span> <span class="fn-c">main</span>(<span class="ty">void</span>) {`, blank: true },
      { id: 'fo', text: `    <span class="kw">for</span> (<span class="ty">int</span> <span class="vr">i</span>=<span class="nm">2</span>; <span class="vr">i</span><=MAX; <span class="vr">i</span>++) {` },
      { id: 'pr1', text: `        <span class="fn-c">printf</span>(<span class="st">"%5d단 출력\\n"</span>, <span class="vr">i</span>);`, indent: 1 },
      { id: 'fi', text: `        <span class="kw">for</span> (<span class="ty">int</span> <span class="vr">j</span>=<span class="nm">2</span>; <span class="vr">j</span><=MAX; <span class="vr">j</span>++)`, indent: 1 },
      { id: 'pr2', text: `            <span class="fn-c">printf</span>(<span class="st">"%d*%d = %2d "</span>, <span class="vr">i</span>, <span class="vr">j</span>, <span class="vr">i</span>*<span class="vr">j</span>);`, indent: 2 },
      { id: 'nl', text: `        <span class="fn-c">printf</span>(<span class="st">"\\n"</span>);`, indent: 1 },
      { text: `    }`, blank: true },
      { id: 'ret', text: `    <span class="kw">return</span> <span class="nm">0</span>;` },
      { text: `}`, blank: true },
    ],
    steps: [
      { line: 'fo', type: 'exec', vars: { i: 2 }, explain: `외부 i=2. 2<=9 → 참.`, output: null },
      { line: 'pr1', type: 'exec', explain: `printf("    2단 출력\\n").`, output: '    2단 출력' },
      { line: 'fi', type: 'exec', vars: { i: 2, j: 2 }, explain: `내부 j=2. 2<=9 → 참.`, output: null },
      { line: 'pr2', type: 'exec', explain: `printf("2*2 =  4 ").`, output: '2*2 =  4 ' },
      { line: 'fi', type: 'exec', vars: { j: 3 }, explain: `j++ → j=3.`, output: null },
      { line: 'pr2', type: 'exec', explain: `2*3=6, 2*4=8, … 2*9=18.`, output: '2*3 =  6 2*4 =  8 … 2*9 = 18 ' },
      { line: 'nl', type: 'exec', explain: `줄바꿈.`, output: '↵' },
      { line: 'fo', type: 'exec', vars: { i: 3 }, explain: `i++ → i=3. 3단.`, output: null },
      { line: 'pr1', type: 'exec', explain: `3단 출력.`, output: '    3단 출력' },
      { line: 'pr2', type: 'exec', explain: `3*2~3*9.`, output: '3*2 =  6 3*3 =  9 … 3*9 = 27 ' },
      { line: 'nl', type: 'exec', explain: `줄바꿈.`, output: '↵' },
      { line: 'fo', type: 'exec', vars: { i: 9 }, explain: `… i=4~9까지. 9단까지 출력.`, output: null },
      { line: 'fo', type: 'exec', vars: { i: 10 }, explain: `i=10, 10<=9? → <span class="e-skip">거짓</span>. 탈출.`, output: null },
      { line: 'ret', type: 'exec', explain: `<b>return 0</b>.`, output: null, memViz: { stack: [], heap: [], totalBytes: 0, released: 'main 프레임 해제' } },
    ]
  },

};
